# Generated by Django 4.2.23 on 2025-07-06 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_usuario_metodos_usuario_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='imageUrl',
            new_name='image_url',
        ),
    ]
