# Generated by Django 4.2.23 on 2025-07-06 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_imageurl_producto_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='precioGeneral',
            new_name='precio_general',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='publicadoPor',
            new_name='publicado_por',
        ),
    ]
