# Generated by Django 4.2.23 on 2025-07-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_preciogeneral_producto_precio_general_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio_general',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
