# Generated by Django 4.2.23 on 2025-07-06 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_producto_precio_general'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('Comida', 'Comida'), ('Hogar', 'Hogar'), ('Electronicos', 'Electronicos'), ('Herramientas', 'Herramientas')]),
        ),
    ]
